### ISSUE TITLE
Command does not match VM vmkfstools article

### ISSUE THREAD

**Issue by flostyen** [LOLESXi-Project/LOLESXi#13]
Hi :-) The description of the following article does not match of „VM listing“: https://lolesxi-project.github.io/LOLESXi/lolesxi/Binaries/vmkfstools/

```
Provides a CSV output of running Virtual Machines with its corresponding WorldID and DisplayName.

vmkfstools -c 10M -d eagerzeroedthick $I/eztDisk > /dev/null
```

Shouldnt that be „esxicli vm list“ or something similar?

**Comment by blueteam0ps** [comment]
@flostyen  thanks for picking  that up. All fixed via https://github.com/LOLESXi-Project/LOLESXi/pull/15
